package com.untilled.roadcapture.utils.constants

object Token {
    const val accessToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1Iiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0MjA3OTEyNCwiZXhwIjoxNjQyMDgyNzI0fQ.A1xZ4tJ11qtQMgtU4RBMUAnUYH89Pgd4dGoWwEKVMmQ"
}